FROM node:16

ENV PORT=9000

WORKDIR /app
RUN npm i http-server -g
COPY dist/spa /app

# pptruser doesn't mean anything here (copy-paste from container with puppeteer)
RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app

# Run everything after as non-privileged user.
USER pptruser

EXPOSE $PORT
CMD http-server ./ -p $PORT
